### ISSUE TITLE
Yubico PIV Manager GUI acts strangely due to PIN issues

### ISSUE THREAD

**Issue by darconeous** [arekinath/PivApplet#29]
I've noticed that the [Yubico PIV Manager GUI][ypivmgr] seems to not like the behavior of the following pin verification code:

https://github.com/arekinath/PivApplet/blob/2297af90eb0d6de7e1c6d1fe4bee973048372c49/src/net/cooperi/pivapplet/PivApplet.java#L1793-L1800

Specifically, it expects to always be able to check the retry counter by sending an empty PIN/PUK. When the Yubico PIV Manager receives a response code of simply `ISO7816.SW_NO_ERROR`, it interprets this as 0 retries left.

`yubico-piv-manager` actually does this too, which you can see here:

```
$ yubico-piv-tool -r "XXX" --action=status
Version:	5.0.0
Serial Number:	-1626252938
CHUID:	3019d4e739da739ced39ce739d836858210842108421384210c3f534106ba710cb7f07fdbe3ea2259ac70c1282350832303330303130313e00fe00
CCC:	f015a000000116ff02383e090b561b6b0c9369e421ddd8f10121f20121f300f40100f50110f600f700fa00fb00fc00fd00fe00
PIN tries left:	5
$
$ yubico-piv-tool -r "XXX" --action=verify-pin -P 123456 --action=status
Successfully verified PIN.
Version:	5.0.0
Serial Number:	-1626252938
CHUID:	3019d4e739da739ced39ce739d836858210842108421384210c3f534106ba710cb7f07fdbe3ea2259ac70c1282350832303330303130313e00fe00
CCC:	f015a000000116ff02383e090b561b6b0c9369e421ddd8f10121f20121f300f40100f50110f600f700fa00fb00fc00fd00fe00
PIN tries left:	0
```

(Note: the negative serial number is being tracked by #28)

While this behavior doesn't really trip up `yubikco-piv-tool` too much, it really makes [Yubico PIV Manager][ypivmgr] practically unusable.

[ypivmgr]: https://developers.yubico.com/yubikey-piv-manager/Releases/

I think a reasonable solution is to replace the above highlighted code with the following:

```
if (lc == 0) {
	ISOException.throwIt((short)(
	    (short)0x63C0 | pin.getTriesRemaining()));
	return;
}
```

This would cause this app to (almost) match the behavior of the real yubikey Neo I have on hand. It differs in that it returns `630X` instead of  `63CX`. I'm not sure what the `C` does, but it doesn't seem to hurt.

-------------------

And, admittedly, I just checked my Yubikey 5 and it is returning `9000` just like your code describes. Yubikey PIV Manager doesn't like it, either.

I'd still consider making the above change for the sake of compatibility.

**Comment by dengert** [comment]
The NIST PIV specs use the PIN verification with Lc=0 to test the login state, as your  applet does. 
Earlier Yubico tokens did not follow the NIST standard and it appears the Yubikey PIV Manager is depending on the non standard behavior. 

Have a look at OpenSC on how it handles these non standard issues, mostly with Yubico:
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-piv.c#L252
and how this is used with a Yubico 4:
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-piv.c#L3376

So your "reasonable solution" is supporting a bug which you point out is fixed in Yubico 5. Actually  fixed in Yubico version 4.3.2

IMHO it would be best to follow the NIST standards if possible, and not perpetuate errors which even Yubico has fixed. Maybe submit bug report to Yubico about [Yubico PIV Manager] (https://developers.yubico.com/yubikey-piv-manager/Releases/)

**Comment by dengert** [comment]
And since you are writing a PIV applet, can you look at the OpenSC `card-piv.c` to see if it needs a new `card->type`  `SC_CARD_TYPE_PIV_II_*` and does it have any of the current `card_issues` or other issues. 

Is there some way to distinguish your applet and its versions? As I understand it, it could be written to may different cards so ATR may not be a good choice.

**Comment by darconeous** [comment]
> So your "reasonable solution" is supporting a bug which you point out is fixed in Yubico 5. Actually fixed in Yubico version 4.3.2

Fair enough.

> And since you are writing a PIV applet ...

I think you may have confused me with someone else.

**Comment by dengert** [comment]
Sorry. 
The "you" in https://github.com/arekinath/PivApplet/issues/29#issuecomment-543760857 should have been addressed to @arekinath 

Also note [yubikey-piv-manager main page](https://developers.yubico.com/yubikey-piv-manager/) says:
"This project is deprecated and is no longer being maintained. Use YubiKey Manager (GUI, CLI) to configure a YubiKey device."

**Comment by darconeous** [comment]
My original suggestion was ill-advised. I agree with all your points. I retract my request and have closed the issue.
