### ISSUE TITLE
Failed commands with device: Something went wrong.

### ISSUE THREAD

**Issue by 424778940z** [arekinath/PivApplet#3]
got error both on windows and linux(ubuntu)

adam@adam-virtual-machine:~/Desktop/yubico-piv-tool$ yubico-piv-tool -r Gemalto -s9a -averify-pin -aimport-certificate < ADAM_ACCOUNT.crt 
>Enter PIN: 
Successfully verified PIN.
Failed commands with device: Something went wrong.

on windows EIDAuthenticate [EID Configuration Wizard] says the smart card is read only

**Comment by arekinath** [comment]
How big is the certificate? The applet is currently limited to fairly small certificates because of the RAM buffer it uses for decoding packets (the limit is set to a little under 1kb, in DER format though not PEM). I've been working on a way around this but haven't got it finished yet.

If it's under 1k of DER, then it'd be great if you could send me the output of the `yubico-piv-tool` command with the `-vvv` option (but you should scrub it of the PIN-related packets and probably not post it publically if the certificate contents are private -- it will contain the full raw APDUs that it's sending to the card)

**Comment by arekinath** [comment]
I've implemented the larger APDU size feature now (up to about 12kb on a J3D081). Will hopefully do a new release shortly and then you can try a new CAP file -- hopefully it will correct your issue. Sorry for the long wait!

**Comment by ntwerdochlib** [comment]
Assuming it is a larger decode buffer you have implemented?  Is this change in a different repo/fork?

**Comment by ntwerdochlib** [comment]
Just realized the card I was using when I ran into this problem had an older PIVApplet installed.  Updating it to one I just built corrects the problem
