### ISSUE TITLE
Admin Auth SW 0x6A80

### ISSUE THREAD

**Issue by ble0** [arekinath/PivApplet#50]
After a fresh install of the applet and running the apdu.script under the test folder, the card always returns 0x6A80 on running this command: 00:87:00:9b:0c:7c:0a:82:08:77:A7:D6:BC:F5:79:62:B9:00 which is the second line of "ask for a challenge for admin auth".
I can not get past to this. Is there any idea or problem I'm not seeing here? I'm using a blank card.

**Comment by ble0** [comment]
I loaded the applet PivApplet-0.9.0-jc222-RESxLD.cap using the generic command: gp -d -install PivApplet-0.9.0-jc222-RESxLD.cap

**Comment by ble0** [comment]
I'm using NXP JCOP3 J2H145 Java Card 3.0.4

**Comment by arekinath** [comment]
The test `apdu.script` in the repository assumes a particular random challenge value (which will be always generated by the simulator). An actual card will return a random value, so that script will not work as-is.

Have you tested it with an actual PIV client like OpenSC, pivy, or yubico-piv-tool?

If you want to run some tests to validate the applet on a card, the `simulator-tests` script uses yubico-piv-tool and pivy, so it should probably work on a freshly installed applet. It covers a lot of the basic operations (though it's a long way from 100%). You give the reader name as the first argument.

**Comment by ble0** [comment]
I'll give a try and let u know, thanks

**Comment by ble0** [comment]
I managed to derive the random challenge
